mqtt: [{host: 'tcp://120.25.30.124:1883',token: 'f64f58790f3f40db88e3bedd83a84290',name: 'test',pwsd: 'test1'},
       {host: 'tcp://47.106.235.93:1883',token: '8fe94a290602468fa8f0be6218024070',name: 'test',pwsd: 'test1'}]

redis:
    host: '111.231.194.143'
    port: '6379'
    auth: 'xyCbwbCcRyjfAHAP'
    accesstoken: 'R29TZXJ2ZXI='
    expiredtime: '1464344863'

rabbitMQ:
    host: '111.231.194.143'
    name: 'GoServer'
    pwsd: 'xyCbwbCcRyjfAHAP'

mysql:
    host: '203.195.209.28'
    port: '3306'
    name: 'GoServer'
    pwsd: 'xyCbwbCcRyjfAHAP'
    basedata: 'GoServer'
    debug: true

web:
    port: ':8888'

system:
    service:
        mqtt: false
        web: true
    log:
        enabel: true
        filepath: './log/'
        filename: 'server'

    timeformat: '2006/01/02 15:04:05'
