mqtt: [ { host: 'tcp://120.25.30.124:1883',token: 'e64f58790f3f40db88e3bedd83a84290',name: 'test',pwsd: 'test1' },
        { host: 'tcp://47.106.235.93:1883',token: 'afe94a290602468fa8f0be6218024070',name: 'test',pwsd: 'test1' } ]

redis:
  host: '203.195.209.28'
  port: '6379'
  auth: 'xyCbwbCcRyjfAHAP'
  maxIdle: 10
  maxOpen: 100
  connect_timeout: 3
  read_timeout: 10
  write_timeout: 10
  idle_timeout: 300

rabbitMQ:
  host: '111.231.194.143'
  name: 'GoServer'
  pwsd: 'xyCbwbCcRyjfAHAP'

mysql:
  host: '172.16.16.3'
  port: '3306'
  name: 'GoServer'
  pwsd: 'xyCbwbCcRyjfAHAP1'
  basedata: 'GoServer'
  debug: false

web:
  port: ':8880'
  runMode: 0  # 0 - debug # 1 - release # 2 - test

system:
  service:
    mqtt: true
    web: true
  log:
    enabel: true
    mqttpath: './log/mqtt/'
    webpath: './log/web/'
    filename: 'server'
  jwt:
    appSecret: 'Jdf4e8hcjvbkjclkjkklfgki843895iojfdnvufh98'
    appIss: 'gisunlink'
    expireTime: 24
  timeformat: '2006/01/02 15:04:05'

  weApp:
    CodeToSessURL: 'https://api.weixin.qq.com/sns/jscode2session?appid={appid}&secret={secret}&js_code={code}&grant_type=authorization_code'
    AppID: 'wx8f1a47ddaa1b61d7'
    AppSecret: '6f33a02967bf71c4e702f8203879de75'


